language: python
python:
    - "2.7"
env:
    - TOX_ENV="py27-dj14"
    - TOX_ENV="py27-dj15"
    - TOX_ENV="py27-dj16" 
    - TOX_ENV="py27-dj17" 
    - TOX_ENV="py27-dj18" 
    - TOX_ENV="coverage"   
install:
    - "pip install tox"
script:
    - "tox -e $TOX_ENV"
notifications:
    email: false
